version: '3.4'

services:
  dockersample:
    image: dockersample
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 9001:9001
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "server.js"]
