version: '3.8'

services:
  dockersample:
    container_name: dami
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    environment:
      NODE_ENV: production
    ports:
      - 9001:9001
  mongo:
    image: mongo
    container_name: app_mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ~/mongo:/data/db
volumes:
  mongodb:
